name: SkinShield
version: 1.0.0
main: vape\skinshield\SkinShield
api: 5.0.0
author: vape (@vapebw, @sxvape)
load: POSTWORLD
permissions:
  skinshield.bypass:
    description: "Bypass skin size and geometry limits"
    default: op
  skinshield.admin:
    description: "Access to /skinshield command"
    default: op

commands:
  skinshield:
    description: "Check skin status or reload plugin"
    permission: skinshield.admin
    aliases: ["ss"]
